# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/company_screener
spring.datasource.username=postgres
spring.datasource.password=22366500

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seed data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# AI API Key
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions